### ISSUE TITLE
keycloak 4.8.3.Final not recognizing a JDBCPING properties clear_table_on_view_change

### ISSUE THREAD

**Issue by abhishekraghav** [moremagic/keycloak-jdbc-ping#7]
I am trying to migrate my keycloak 3.4.3 to 4.8.3, but looks like the underlying services we use with keycloak have removed support for one of the property. Looks like they have upgraded the jgroups version. Can you suggest any workaround for clearing the table when view gets changed as I am ending up with lot of stale entries as we run our keycloak in cloud env where the nodes are not fixed.

```
2019-04-24 06:56:02,657 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 53)  KEYCLOAK DEV MSC000001: Failed to start service org.wildfly.clustering.jgroups.channel.ee: org.jboss.msc.service.StartException in service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.lang.IllegalArgumentException: java.security.PrivilegedActionException: java.lang.IllegalArgumentException: Unrecognized JDBC_PING properties: [clear_table_on_view_change] 

at org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:70) at org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117) 

at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985) 

at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378) at java.lang.Thread.run(Thread.java:748) 


at org.jboss.threads.JBossThread.run(JBossThread.java:485) Caused by: java.lang.IllegalStateException: java.lang.IllegalArgumentException: java.security.PrivilegedActionException: java.lang.IllegalArgumentException: Unrecognized JDBC_PING properties: [clear_table_on_view_change]

```

**Comment by moremagic** [comment]
Thanks for the report

With Keycloak 4.5.0.Final or later (all versions of JGroups 4.0.0 or later)
The clear_table_on_view_change property is no longer available
https://issues.jboss.org/browse/JGRP-1906

Here it seems like the problem has been solved in this way
https://github.com/moremagic/keycloak-jdbc-ping/pull/6

In addition, it seems that Document has not been corrected yet.
https://github.com/belaban/JGroups/blame/master/doc/manual/protocols.adoc#L601
